/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;

import com.rpl.rama.Depot;
import com.rpl.rama.test.InProcessCluster;

import java.util.List;

class CoreTest {
    @Test void contactTest(TestInfo testInfo) throws Exception {
        try(InProcessCluster ipc = InProcessCluster.create()) {
            Core coreModule = new Core();
            TestHelpers.launchModule(ipc, coreModule, testInfo);

            String coreModuleName = coreModule.getClass().getName();

            Depot contactDepot = ipc.clusterDepot(coreModuleName, "*contactDepot");

            Core.Contact optometrist = new Core.Contact("Optometrist", "1800Optometrist");
            contactDepot.append(optometrist);

            Core.Contact dentist = new Core.Contact("Dentist", "1800Dentist");
            contactDepot.append(dentist);
        }
    }
}
