/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.*;

import com.rpl.rama.Depot;
import com.rpl.rama.QueryTopologyClient;
import com.rpl.rama.test.InProcessCluster;

class CoreTest {
    @Test void contactTest(TestInfo testInfo) throws Exception {
        try(InProcessCluster ipc = InProcessCluster.create()) {
            Core coreModule = new Core();
            TestHelpers.launchModule(ipc, coreModule, testInfo);

            String coreModuleName = coreModule.getClass().getName();

            Depot contactDepot = ipc.clusterDepot(coreModuleName, "*contactDepot");

            contactDepot.append(new Core.Contact("Optometrist", "1800Contacts"));
        
            assertEquals(null, null);
        }
    }
}
