/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.rpl.rama.Depot;
import com.rpl.rama.RamaModule;

public class Core implements RamaModule {
    public static class Contact {
        public String contactName;
        public String phoneNumber; 
    }

    @Override
    public void define(Setup setup, Topologies topologies) {
        setup.declareDepot("*contactDepot", Depot.random());
    }
}
