/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

import com.rpl.rama.Depot;
import com.rpl.rama.PState;
import com.rpl.rama.Path;
import com.rpl.rama.RamaModule;
import com.rpl.rama.RamaSerializable;
import com.rpl.rama.helpers.TopologyUtils;
import com.rpl.rama.integration.TaskGlobalContext;
import com.rpl.rama.integration.TaskGlobalObject;
import com.rpl.rama.module.StreamTopology;

public class Core implements RamaModule {

    public static class ContactsBook implements TaskGlobalObject {

        public List<Contact> contacts;

        @Override
        public void prepareForTask(int taskId, TaskGlobalContext context) {
            contacts = new ArrayList<>();
        }

        public Object addContact(Contact contact) {
            contacts.add(contact);
            return null;
        }

        @Override
        public void close() {
        }
    }

    public static class Contact implements RamaSerializable {
        public String contactName;
        public String phoneNumber;

        // Required by RamaSerializable for deserialization
        public Contact() {}

        public Contact(String contactName, String phoneNumber) {
            this.contactName = contactName;
            this.phoneNumber = phoneNumber;
        }
    }

    @Override
    public void define(Setup setup, Topologies topologies) {
        setup.declareDepot("*contactDepot", Depot.random());

        StreamTopology st = topologies.stream("contactsBook");
        st.pstate("$$contactsByName", PState.mapSchema(String.class, Contact.class));
        st.pstate("$$contactsByNumber", PState.mapSchema(String.class, Contact.class));

        st.source("*contactDepot").out("*contact")
          .macro(TopologyUtils.extractJavaFields("*contact", "*contactName", "*phoneNumber"))
          .localTransform("$$contactsByName", Path.key("*contactName").termVal("*contact"))
          .localTransform("$$contactsByNumber", Path.key("*phoneNumber").termVal("*contact"));

    }
}
