/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

class Core {
    @Test void someLibraryMethodReturnsTrue() {
        Core classUnderTest = new Core();
    }
}
